// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: proto/streaming_voice/streaming_voice.proto

package stt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByteBuff      []byte                 `protobuf:"bytes,1,opt,name=byte_buff,json=byteBuff,proto3" json:"byte_buff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRequest) Reset() {
	*x = VoiceRequest{}
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRequest) ProtoMessage() {}

func (x *VoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRequest.ProtoReflect.Descriptor instead.
func (*VoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_voice_streaming_voice_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceRequest) GetByteBuff() []byte {
	if x != nil {
		return x.ByteBuff
	}
	return nil
}

type TextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Segment       int32                  `protobuf:"varint,2,opt,name=segment,proto3" json:"segment,omitempty"`                                   // Số 2
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                                              // Số 3
	Result        *Result                `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                      // Số 4
	SegmentStart  float32                `protobuf:"fixed32,5,opt,name=segment_start,json=segmentStart,proto3" json:"segment_start,omitempty"`    // Số 5
	SegmentLength float32                `protobuf:"fixed32,6,opt,name=segment_length,json=segmentLength,proto3" json:"segment_length,omitempty"` // Số 6
	TotalLength   float32                `protobuf:"fixed32,7,opt,name=total_length,json=totalLength,proto3" json:"total_length,omitempty"`       // Số 7
	Msg           string                 `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`                                            // Số 8 (Quan trọng: Server Viettel để msg ở số 8)
	AudioUrl      string                 `protobuf:"bytes,9,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextReply) Reset() {
	*x = TextReply{}
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReply) ProtoMessage() {}

func (x *TextReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReply.ProtoReflect.Descriptor instead.
func (*TextReply) Descriptor() ([]byte, []int) {
	return file_proto_streaming_voice_streaming_voice_proto_rawDescGZIP(), []int{1}
}

func (x *TextReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TextReply) GetSegment() int32 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *TextReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextReply) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TextReply) GetSegmentStart() float32 {
	if x != nil {
		return x.SegmentStart
	}
	return 0
}

func (x *TextReply) GetSegmentLength() float32 {
	if x != nil {
		return x.SegmentLength
	}
	return 0
}

func (x *TextReply) GetTotalLength() float32 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *TextReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TextReply) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hypotheses    []*Result_Hypothese    `protobuf:"bytes,1,rep,name=hypotheses,proto3" json:"hypotheses,omitempty"`
	Final         bool                   `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_streaming_voice_streaming_voice_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetHypotheses() []*Result_Hypothese {
	if x != nil {
		return x.Hypotheses
	}
	return nil
}

func (x *Result) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type Result_Hypothese struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Transcript                 string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	TranscriptNormed           string                 `protobuf:"bytes,2,opt,name=transcript_normed,json=transcriptNormed,proto3" json:"transcript_normed,omitempty"`
	TranscriptUrlencoded       string                 `protobuf:"bytes,3,opt,name=transcript_urlencoded,json=transcriptUrlencoded,proto3" json:"transcript_urlencoded,omitempty"`
	TranscriptNormedUrlencoded string                 `protobuf:"bytes,4,opt,name=transcript_normed_urlencoded,json=transcriptNormedUrlencoded,proto3" json:"transcript_normed_urlencoded,omitempty"`
	Confidence                 float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Likelihood                 float32                `protobuf:"fixed32,6,opt,name=likelihood,proto3" json:"likelihood,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Result_Hypothese) Reset() {
	*x = Result_Hypothese{}
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result_Hypothese) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Hypothese) ProtoMessage() {}

func (x *Result_Hypothese) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_voice_streaming_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Hypothese.ProtoReflect.Descriptor instead.
func (*Result_Hypothese) Descriptor() ([]byte, []int) {
	return file_proto_streaming_voice_streaming_voice_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Result_Hypothese) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *Result_Hypothese) GetTranscriptNormed() string {
	if x != nil {
		return x.TranscriptNormed
	}
	return ""
}

func (x *Result_Hypothese) GetTranscriptUrlencoded() string {
	if x != nil {
		return x.TranscriptUrlencoded
	}
	return ""
}

func (x *Result_Hypothese) GetTranscriptNormedUrlencoded() string {
	if x != nil {
		return x.TranscriptNormedUrlencoded
	}
	return ""
}

func (x *Result_Hypothese) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Result_Hypothese) GetLikelihood() float32 {
	if x != nil {
		return x.Likelihood
	}
	return 0
}

var File_proto_streaming_voice_streaming_voice_proto protoreflect.FileDescriptor

const file_proto_streaming_voice_streaming_voice_proto_rawDesc = "" +
	"\n" +
	"+proto/streaming_voice/streaming_voice.proto\x12\x0fstreaming_voice\"+\n" +
	"\fVoiceRequest\x12\x1b\n" +
	"\tbyte_buff\x18\x01 \x01(\fR\bbyteBuff\"\x9c\x02\n" +
	"\tTextReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\asegment\x18\x02 \x01(\x05R\asegment\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12/\n" +
	"\x06result\x18\x04 \x01(\v2\x17.streaming_voice.ResultR\x06result\x12#\n" +
	"\rsegment_start\x18\x05 \x01(\x02R\fsegmentStart\x12%\n" +
	"\x0esegment_length\x18\x06 \x01(\x02R\rsegmentLength\x12!\n" +
	"\ftotal_length\x18\a \x01(\x02R\vtotalLength\x12\x10\n" +
	"\x03msg\x18\b \x01(\tR\x03msg\x12\x1b\n" +
	"\taudio_url\x18\t \x01(\tR\baudioUrl\"\xf3\x02\n" +
	"\x06Result\x12A\n" +
	"\n" +
	"hypotheses\x18\x01 \x03(\v2!.streaming_voice.Result.HypotheseR\n" +
	"hypotheses\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\x1a\x8f\x02\n" +
	"\tHypothese\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12+\n" +
	"\x11transcript_normed\x18\x02 \x01(\tR\x10transcriptNormed\x123\n" +
	"\x15transcript_urlencoded\x18\x03 \x01(\tR\x14transcriptUrlencoded\x12@\n" +
	"\x1ctranscript_normed_urlencoded\x18\x04 \x01(\tR\x1atranscriptNormedUrlencoded\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"likelihood\x18\x06 \x01(\x02R\n" +
	"likelihood2Y\n" +
	"\vStreamVoice\x12J\n" +
	"\tSendVoice\x12\x1d.streaming_voice.VoiceRequest\x1a\x1a.streaming_voice.TextReply(\x010\x01B$Z\"voicebot/proto/streaming_voice;sttb\x06proto3"

var (
	file_proto_streaming_voice_streaming_voice_proto_rawDescOnce sync.Once
	file_proto_streaming_voice_streaming_voice_proto_rawDescData []byte
)

func file_proto_streaming_voice_streaming_voice_proto_rawDescGZIP() []byte {
	file_proto_streaming_voice_streaming_voice_proto_rawDescOnce.Do(func() {
		file_proto_streaming_voice_streaming_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streaming_voice_streaming_voice_proto_rawDesc), len(file_proto_streaming_voice_streaming_voice_proto_rawDesc)))
	})
	return file_proto_streaming_voice_streaming_voice_proto_rawDescData
}

var file_proto_streaming_voice_streaming_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_streaming_voice_streaming_voice_proto_goTypes = []any{
	(*VoiceRequest)(nil),     // 0: streaming_voice.VoiceRequest
	(*TextReply)(nil),        // 1: streaming_voice.TextReply
	(*Result)(nil),           // 2: streaming_voice.Result
	(*Result_Hypothese)(nil), // 3: streaming_voice.Result.Hypothese
}
var file_proto_streaming_voice_streaming_voice_proto_depIdxs = []int32{
	2, // 0: streaming_voice.TextReply.result:type_name -> streaming_voice.Result
	3, // 1: streaming_voice.Result.hypotheses:type_name -> streaming_voice.Result.Hypothese
	0, // 2: streaming_voice.StreamVoice.SendVoice:input_type -> streaming_voice.VoiceRequest
	1, // 3: streaming_voice.StreamVoice.SendVoice:output_type -> streaming_voice.TextReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_streaming_voice_streaming_voice_proto_init() }
func file_proto_streaming_voice_streaming_voice_proto_init() {
	if File_proto_streaming_voice_streaming_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streaming_voice_streaming_voice_proto_rawDesc), len(file_proto_streaming_voice_streaming_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_streaming_voice_streaming_voice_proto_goTypes,
		DependencyIndexes: file_proto_streaming_voice_streaming_voice_proto_depIdxs,
		MessageInfos:      file_proto_streaming_voice_streaming_voice_proto_msgTypes,
	}.Build()
	File_proto_streaming_voice_streaming_voice_proto = out.File
	file_proto_streaming_voice_streaming_voice_proto_goTypes = nil
	file_proto_streaming_voice_streaming_voice_proto_depIdxs = nil
}
