// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.6.1
// source: proto/streaming_voice/streaming_voice.proto

package stt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamVoice_SendVoice_FullMethodName = "/streaming_voice.StreamVoice/SendVoice"
)

// StreamVoiceClient is the client API for StreamVoice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamVoiceClient interface {
	SendVoice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VoiceRequest, TextReply], error)
}

type streamVoiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamVoiceClient(cc grpc.ClientConnInterface) StreamVoiceClient {
	return &streamVoiceClient{cc}
}

func (c *streamVoiceClient) SendVoice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VoiceRequest, TextReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamVoice_ServiceDesc.Streams[0], StreamVoice_SendVoice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VoiceRequest, TextReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamVoice_SendVoiceClient = grpc.BidiStreamingClient[VoiceRequest, TextReply]

// StreamVoiceServer is the server API for StreamVoice service.
// All implementations must embed UnimplementedStreamVoiceServer
// for forward compatibility.
type StreamVoiceServer interface {
	SendVoice(grpc.BidiStreamingServer[VoiceRequest, TextReply]) error
	mustEmbedUnimplementedStreamVoiceServer()
}

// UnimplementedStreamVoiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamVoiceServer struct{}

func (UnimplementedStreamVoiceServer) SendVoice(grpc.BidiStreamingServer[VoiceRequest, TextReply]) error {
	return status.Error(codes.Unimplemented, "method SendVoice not implemented")
}
func (UnimplementedStreamVoiceServer) mustEmbedUnimplementedStreamVoiceServer() {}
func (UnimplementedStreamVoiceServer) testEmbeddedByValue()                     {}

// UnsafeStreamVoiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamVoiceServer will
// result in compilation errors.
type UnsafeStreamVoiceServer interface {
	mustEmbedUnimplementedStreamVoiceServer()
}

func RegisterStreamVoiceServer(s grpc.ServiceRegistrar, srv StreamVoiceServer) {
	// If the following call panics, it indicates UnimplementedStreamVoiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamVoice_ServiceDesc, srv)
}

func _StreamVoice_SendVoice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamVoiceServer).SendVoice(&grpc.GenericServerStream[VoiceRequest, TextReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamVoice_SendVoiceServer = grpc.BidiStreamingServer[VoiceRequest, TextReply]

// StreamVoice_ServiceDesc is the grpc.ServiceDesc for StreamVoice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamVoice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming_voice.StreamVoice",
	HandlerType: (*StreamVoiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendVoice",
			Handler:       _StreamVoice_SendVoice_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/streaming_voice/streaming_voice.proto",
}
